[nixpacks]
plan = '''
  [environment]
  NIXPACKS_METADATA = "railway"

  [phases.setup]
  nixPkgs = [
    "gcc",
    "libdrm",
    "libxkbcommon",
    "libglvnd",
    "libxshmfence",
    "dbus",
    "cups",
    "libxrandr",
    "libxcomposite",
    "libxdamage",
    "libxrender",
    "libxfixes",
    "libxext",
    "at-spi2-atk",
    "at-spi2-core",
    "gtk3",
    "glib",
    "ffmpeg-full"
  ]
'''
